version: "2"
services:
  web:
    image: server_web
    ports:
      - "4000:4000"
    links:
      - mongo
  client: 
    image: client
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"